### ISSUE TITLE
skimage.measure.compare_ssim not present in current version of skimage 

### ISSUE THREAD

**Issue by findalexli** [skycrapers/TecoGAN-PyTorch#27]
I was having issues with 
Traceback (most recent call last):
  File "/home/alex/TecoGAN-PyTorch/./codes/main.py", line 9, in <module>
    from models import define_model
  File "/home/alex/TecoGAN-PyTorch/codes/models/__init__.py", line 1, in <module>
    from .vsr_model import VSRModel
  File "/home/alex/TecoGAN-PyTorch/codes/models/vsr_model.py", line 7, in <module>
    from .networks import define_generator
  File "/home/alex/TecoGAN-PyTorch/codes/models/networks/__init__.py", line 1, in <module>
    from .tecogan_nets import FRNet, SpatioTemporalDiscriminator, SpatialDiscriminator
  File "/home/alex/TecoGAN-PyTorch/codes/models/networks/tecogan_nets.py", line 12, in <module>
    from metrics.model_summary import register, parse_model_info
  File "/home/alex/TecoGAN-PyTorch/codes/metrics/__init__.py", line 1, in <module>
    from .metric_calculator import MetricCalculator
  File "/home/alex/TecoGAN-PyTorch/codes/metrics/metric_calculator.py", line 13, in <module>
    from .LPIPS.models.dist_model import DistModel
  File "/home/alex/TecoGAN-PyTorch/codes/metrics/LPIPS/models/__init__.py", line 7, in <module>
    from skimage.measure import compare_ssim
ImportError: cannot import name 'compare_ssim' from 'skimage.measure' (/home/alex/anaconda3/envs/fastai/lib/python3.9/site-packages/skimage/measure/__init__.py)

According to the following post, the replacing the import with structural_similarity replacement works 
https://stackoverflow.com/a/67966335

**Comment by themis0888** [comment]
You can fix this problem by replacing 
'from skimage.measure import compare_ssim'
to 
'from skimage.metrics import structural_similarity as compare_ssim'
in 'TecoGan-PyTorch/codes/metrics/LPIPS/models/__init__.py'

**Comment by ghost** [comment]
You can fix this problem by replacing
`from skimage.measure import compare_ssim`
to
`from skimage.metrics import structural_similarity as compare_ssim`
in `TecoGan-PyTorch/codes/metrics/LPIPS/models/__init__.py`
